#포트번호 지정
server:
  port: 8085

#타임리프를 사용할 경로를 지정해 주어야 templates아래 html파일을 찾아간다.
#devtools : 정적 리소스를 자동으로 서버를 재실행 하지 않아도 해주기 위한 코드
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/




